### ISSUE TITLE
Download with authentication

### ISSUE THREAD

**Issue by CasualX** [marklieberman/downloadstar#55] opened 2018-09-09 15:18 UTC
Hello,

I am trying to mass download documents from a CMS where the built in download tools suck, so I am trying to solve my problem with Download Star (after finding out that DownThemAll! is no longer working).

The page I am trying to work with contains a list of documents and for each entry contains (among other things) a download link. All the download links contain the text `tool_action=downloader`.

Filtering these links with Download Star works just fine however after download I am left with contents of a .html file which when opened contain a login form. It is as if the authentication cookies do not transfer to the Download Star downloads.

Am I missing something? Is this use case supported by Download Star?

Thanks.

**Comment by marklieberman** [comment] 2018-09-09 17:04
Cookies are not added to the download requests at this time, so downloads often don't work for sites with auth checks. 

The problem is that the web extension API [download.download()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) doesn't automatically add cookies for a domain to the download requests. Although you can manually set headers on the download, you cannot set the Cookie header because it is on the [forbidden headers list](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name).

When I have some more free time I will investigate further to see if there are any work-arounds.

**Comment by marklieberman** [comment] 2019-07-14 05:34
Closing in favour of #72 that has more information.

**Closed by marklieberman** 2019-07-14 05:34 UTC
Labels: api limitation
